config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('pedido/', include('pedido.urls')),
    path('perfil/', include('perfil.urls')),
       

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path
from . import views


app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
    path('lista/', views.Lista.as_view(), name='lista'),
]

perfil/urls.py
from django.urls import path
from . import views


app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProduto.as_view(), name='lista'),
    path('<slug>', views.DetalheProduto.as_view(), name='detalhe'),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(), name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(), name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),
    path('busca/', views.Busca.as_view(), name='busca'),
]

perfil/models.py
from django.db import models
from django.contrib.auth.models import User
from utils.valida_cpf import validar_cpf
import re
from django.forms import ValidationError


class PerfilUsuario(models.Model):
    usuario = models.ForeignKey(User, on_delete= models.CASCADE, verbose_name= 'usuário')
    idade = models.PositiveIntegerField()
    cpf =models.CharField(max_length= 11)
    endereco = models.CharField(max_length= 50, verbose_name= 'endereço')
    numero =models.CharField(max_length= 5, verbose_name='número')
    complemento = models.CharField(max_length= 30)
    bairro =models.CharField(max_length= 30)
    cep = models.CharField(max_length= 8)
    cidade = models.CharField(max_length= 30)
    estado = models.CharField(
        max_length= 2,
        default= 'SP',
        choices= (
            ('AC', 'Acre'),
            ('AL', 'Alagoas'),
            ('AP', 'Amapá'),
            ('AM', 'Amazonas'),
            ('BA', 'Bahia'),
            ('CE', 'Ceará'),
            ('DF', 'Distrito Federal'),
            ('ES', 'Espírito Santo'),
            ('GO', 'Goiás'),
            ('MA', 'Maranhão'),
            ('MT', 'Mato Grosso'),
            ('MS', 'Mato Grosso do Sul'),
            ('MG', 'Minas Gerais'),
            ('PA', 'Pará'),
            ('PB', 'Paraíba'),
            ('PR', 'Paraná'),
            ('PE', 'Pernambuco'),
            ('PI', 'Piauí'),
            ('RJ', 'Rio de Janeiro'),
            ('RN', 'Rio Grande do Norte'),
            ('RS', 'Rio Grande do Sul'),
            ('RO', 'Rondônia'),
            ('RR', 'Roraima'),
            ('SC', 'Santa Catarina'),
            ('SP', 'São Paulo'),
            ('SE', 'Sergipe'),
            ('TO', 'Tocantins'),
            
        )
    )
    
    def __str__(self) -> str:
        return f'{self.usuario}'
    
    
    # Adicionando mensagens de erros nos formulários
    def clean(self) -> None:
        erros_messages= {}
        
        if not validar_cpf(self.cpf):
            erros_messages['cpf'] = 'CPF inválido'
            
        if re.search(r'[^0-9]', self.cep):
            erros_messages['cep'] = 'Digite apenas números'
        
        if len(self.cep) < 8:
            erros_messages['cep'] = 'CEP precisa ter 8 digitos.'
            
        if erros_messages:
            raise ValidationError(erros_messages)
    
    class Meta:
        verbose_name_plural = 'Perfis'

produto/models.py
from django.db import models
from PIL import Image
import os
from django.conf import settings
from django.utils.text import slugify

class Produto(models.Model):    
    
    nome = models.CharField(max_length= 255)
    descricao_curta = models.TextField(max_length= 255)
    descricao_longa = models.TextField()
    imagem = models.ImageField(upload_to= 'produto_imagens/%Y/%m')
    slug =models.SlugField(unique= True, blank= True, null= True)
    preco_marketing = models.FloatField()
    preco_marketing_promocional = models.FloatField(default= 0)
    tipo = models.CharField(default= 'V',
                            max_length= 1,
                            choices= (('V', 'Variável'),
                                      ('S', 'Simples'),
                                           )
                            )    
    
    def __str__(self) -> str:
        return self.nome
    
    
    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug
            
        super().save(*args, **kwargs)
    
        self.resize_image(self.imagem.name, 800)
        
    
    @staticmethod
    def resize_image(path_image, new_width= 800):
        image_path = os.path.join(settings.MEDIA_ROOT, path_image)        
        img = Image.open(image_path)
        width, heigth = img.size
        
        if width <= new_width:
            img.close()
            return
        
        new_heigth = round((new_width * heigth) / width)
        new_img = img.resize((new_width, new_heigth), Image.LANCZOS)
        new_img.save(image_path,
                     optimize= True,
                     quality = 60,)
        img.close()
        

class Variacao(models.Model):
    nome = models.CharField(max_length= 255)   
    produto = models.ForeignKey(Produto, on_delete= models.CASCADE)
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)
    
    def __str__(self) -> str:
        return f'{self.nome} | {self.produto}'
    
    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'Varições'

    

produto/views.py
from django.shortcuts import render, redirect, get_object_or_404
from perfil.models import PerfilUsuario
from .models import Produto, Variacao
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from django.urls import reverse
from django.db.models import Q


class ListaProduto(ListView):
    model = Produto
    template_name= 'lista.html'    
    # paginate_by = 6
    context_object_name = 'produtos'
    
   
class DetalheProduto(DetailView):
    model = Produto
    template_name = 'detalhe.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'
    
    
class AdicionarAoCarrinho(View):
    def get(self, *args, **kwargs):
        # retornar a página para anterior
        http_referer = self.request.META.get('HTTP_REFERER', reverse('produto:lista'))
        # obter o valor do vid da url
        variacao_id = self.request.GET.get('vid')
        
        if not variacao_id:
            messages.error(self.request, 'Produto não existe')
            return redirect(http_referer)
        
        variacao = get_object_or_404(Variacao, id= variacao_id)
        produto = variacao.produto
        variacao_estoque = variacao.estoque
        
        produto_id = produto.id
        produto_nome = produto.nome
        variacao_nome = variacao.nome
        preco_unitario = variacao.preco
        preco_unitario_promocional = variacao.preco_promocional
        quantidade = 1
        slug = produto.slug
        imagem = produto.imagem
        imagem = imagem.name
        
        
        # VERIFICADO ESTOQUE
        if variacao.estoque < 1:
            messages.error(self.request, 'Estoque insulficiente.')
            return redirect(http_referer)
        
        # CRIANDO SESSION
        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()
            
        carrinho = self.request.session['carrinho']
        
        if variacao_id in carrinho:
            quantidade_carrinho = carrinho[variacao_id]['quantidade']
            quantidade_carrinho += 1
            
            if variacao_estoque < quantidade_carrinho:
                messages.error(self.request, f'Desculpe. Só temos {variacao_estoque} em estoque.')
                quantidade_carrinho = variacao_estoque
                return redirect(http_referer)         
            
            carrinho[variacao_id]['quantidade'] = quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo'] = preco_unitario * quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo_promocional'] = preco_unitario_promocional * quantidade_carrinho
            
        else:
            carrinho[variacao_id] = {
                'produto_id' : produto_id,
                'produto_nome' : produto_nome,
                'variacao_nome' : variacao_nome,
                'variacao_id' : variacao_id,
                'preco_unitario' : preco_unitario,
                'preco_unitario_promocional' : preco_unitario_promocional,
                'preco_quantitativo': preco_unitario,
                'preco_quantitativo_promocional': preco_unitario_promocional,
                'quantidade' : quantidade,
                'slug' : slug,
                'imagem' : imagem,
            }
            
        self.request.session.save()       
        
        # TODO: falha ao adicionar mensagem de adicionar ao carrinho
        messages.success(self.request,
                         f'{produto_nome} {variacao_nome} '
                         f'foi adicionado com sucesso {quantidade}x.')
        return redirect(http_referer)
    
    
class RemoverDoCarrinho(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get('HTTP_REFERER')
        variacao_id = self.request.GET.get('vid')
         
        if not variacao_id:
            return redirect(http_referer)
        
        if not self.request.session.get('carrinho'):
            return redirect(http_referer) 
        
        if variacao_id not in self.request.session['carrinho']:
            return redirect(http_referer)
        
        carrinho = self.request.session['carrinho'][variacao_id]
        
        messages.success(self.request, 
                         f'O Produto {carrinho["produto_nome"]} {carrinho["variacao_nome"]} foi removido com sucesso.')
        del self.request.session['carrinho'][variacao_id]
        self.request.session.save()
        
        return redirect(http_referer)
    
    
class Carrinho(ListaProduto):
    def get(self, *args, **kwargs):
        carrinho = self.request.session.get('carrinho')
                        
        return render(self.request, 'carrinho.html', {'carrinho': carrinho})
    
    
class ResumoDaCompra(ListaProduto):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')
        
        perfil = PerfilUsuario.objects.filter(usuario= self.request.user).exists()
        
        if not perfil:
            messages.error(self.request, 'Informações incompletas, por favor atualizar cadastro.')
            return redirect('perfil:criar')
        
        if not self.request.session.get('carrinho'):
            messages.error(self.request, 'Não existe itens no seu carrinho de compras.')
            return redirect('produto:lista')
        
        contexto ={
            'usuario': self.request.user,
            'carrinho': self.request.session['carrinho'],
        }
        # TODO: falta enviar os dados do usuário no html
        
        return render(self.request, 'resumodacompra.html', contexto)
    
class Busca(ListaProduto):
    def get_queryset(self, *args, **kwargs):
        termo = self.request.GET.get('termo') or self.request.session['termo']        
                
        qs =  super().get_queryset(*args, **kwargs)
        
        if not termo:
            return qs
        
        self.request.session['termo'] = termo
            
        qs = qs.filter(
            Q(nome__icontains= termo) |
            Q(descricao_curta__icontains= termo) |
            Q(descricao_longa__icontains= termo)             
        )

        self.request.session.save()
        return qs
        
        

produto/templates/carrinho.html
{% extends 'base.html' %}
{% load filters %}
{% load static %}

{% block title %}Carrinho{% endblock title %}

{% block body %}


{% include 'parciais/_messages.html' %}
{% if carrinho %}
<div class="row mt-3">
    <div class="col">
        <h3>Carrinho de compras</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        {% include 'parciais/_carrinho.html' %}
        
    </div>
</div>



<div class="row mt-3">
    <div class="col-lg">
        <p class='lead'>Total no carrinho</p>

        <div class='table-responsive'>
            <table class="table">
                <tr>
                    <td class="font-weight-bold">Total</td>
                    <td>{{carrinho|cart_total_preco|estilo_moeda}}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-lg mt-auto">
        {% if request.user.is_authenticated %}
        <a class="btn btn-lg btn-block btn-primary" href="{% url 'produto:resumodacompra' %}">
            Finalizar a compra
        </a>
        {% else %}
        <a class="btn btn-lg btn-block btn-primary" href="{% url 'perfil:criar' %}">
            Finalizar a compra
        </a>
        {% endif %}
    </div>
</div>

{% else %}
<div class="row mt-3">
    <div class="col">
        <h3>Carrinho vazio</h3>
        <p class="lead">Não a produtos no carrinho.</p>
    </div>
</div>

{% endif %}

{% endblock body %}

produto/templates/detalhe.html
{% extends 'base.html' %}
{% load filters %}


{% block title %}{{produto.nome}}{% endblock title %}

{% block body %}
{% include 'parciais/_messages.html' %}
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg">
                <div class="row no-gutters">
                    <div class="col-lg-12">
                        <img class="img-fluid" src="{{produto.imagem.url}}" alt="{{produto.nome}}">
                    </div>
                </div>
            </div>
            <div class="col-lg">
                <div class="mt-4 mt-lg-0">
                    <h1 class="h2">{{produto.nome}}</h1>
                    <p class="lead">{{produto.descricao_curta|linebreaks}}</p>
                    <p class="lead">
                        {% if produto.preco_marketing_promocional %}
                            <span id="variation-preco" class="lead product-price">{{produto.preco_marketing_promocional|estilo_moeda}}</span>
                            <span id="variation-preco-promocional"
                                class="lead product-old-price text-muted">{{produto.preco_marketing|estilo_moeda}}</span>
                        {% else %}
                            <span id="variation-preco" class="lead product-price">{{produto.preco_marketing|estilo_moeda}}</span>
                        {% endif %}
                    </p>

                    <form action="{% url 'produto:adicionaraocarrinho' %}" id="form-add-to-cart">
                        <div class="form-group">
                            <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                                {% for variacao in produto.variacao_set.all %}
                                    {% if variacao.preco_promocional %}                            
                                    <option data-preco="{{variacao.preco_promocional|estilo_moeda}}" data-preco-promocional="{{variacao.preco|estilo_moeda}}" 
                                    value="{{variacao.id}}">{{variacao.nome}}
                                    </option>
                                    {% else %}
                                    <option data-preco="{{variacao.preco|estilo_moeda}}"  
                                    value="{{variacao.id}}">{{variacao.nome}}
                                    </option>
                                    {% endif %} 
                                {% endfor %}
                            </select>
                        </div>

                        <div class="text-left">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Adicionar ao carrinho
                            </button>
                        </div>

                    </form>


                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-12">
                <div class="mt-5 mb-5">
                    <h2 class="text-center">{{produto.nome}}</h2>
                    <p>{{produto.descricao_longa|linebreaks}}</p>
                </div>
            </div>
        </div>

    </div>
</div>

{% include 'parciais/_pagination.html' %}

{% endblock body %}

produto/templates/lista.html
{% extends 'base.html' %}
{% load filters %}


{% block title %}Lista de Produtos{% endblock title %}

{% block body %}
<div class="row">
    <div class="col-lg-12">        
        {% include 'parciais/_messages.html' %}

        <div class="card-columns">
            {% for produto in produtos%}
                <div class="card">
                    <a href="{% url 'produto:detalhe' produto.slug %}">
                        <img class="card-img-top " src="{{produto.imagem.url}}" alt="{{produto.nome}}">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">{{produto.nome}}</h5>
                        <p class="card-text">{{produto.descricao_curta}}</p>
                        <div class="container product-price-block text-center">

                            {% if produto.preco_marketing_promocional %}
                                <span class="product-price">
                                    {{produto.preco_marketing_promocional|estilo_moeda}}
                                </span>
                                <span class="product-old-price text-muted">
                                    {{produto.preco_marketing|estilo_moeda}}
                                </span>
                            {% else %}
                            <span class="product-price">
                                {{produto.preco_marketing|estilo_moeda}}
                            </span>
                            {% endif %}
                            
                        </div>
                    </div>
                    <div class="card-footer bg-transparent border-top-light-custom text-center">
                        <a href="{% url 'produto:detalhe' produto.slug %}" class="btn btn-primary btn-sm m-1 btn-block">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            Comprar
                        </a>
                    </div>
                </div>
                
            {% endfor %}

        </div>
    </div>
</div>

{% include 'parciais/_pagination.html' %}

{% endblock body %}

produto/templates/resumodacompra.html
{% extends 'base.html' %}
{% load filters %}

{% block title %}Resumo da Compra{% endblock title %}

{% block body %}

<div class="row mb-5">
    <div class="col-lg">
        <h2>Resumo da sua compra</h2>
        
        <p class="lead">Dados do usuário</p>
        <p>Caso precise editar, <a href="{% url 'perfil:criar' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{usuario.first_name}}</dd>
            <dt class="col-lg-2">Sobrenome:</dt>
            <dd class="col-lg-4">{{usuario.last_name}}</dd>

            <dt class="col-lg-2">Idade:</dt>
            <dd class="col-lg-4">{{usuario.perfilusuario_set.idade}}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">30 de Abril de 1898</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">11111111111</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{usuario.email}}</dd>
        </dl>

        <p class="lead">Dados de endereço</p>
        <p>Caso precise editar, <a href="{% url 'perfil:criar' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Endereço:</dt>
            <dd class="col-lg-4">Av. Filho Junior</dd>
            <dt class="col-lg-2">Número:</dt>
            <dd class="col-lg-4">12</dd>

            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">Casa</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">Centro</dd>

            <dt class="col-lg-2">Cidade:</dt>
            <dd class="col-lg-4">São Paulo</dd>
            <dt class="col-lg-2">Estado:</dt>
            <dd class="col-lg-4">SP</dd>

            <dt class="col-lg-2">CEP:</dt>
            <dd class="col-lg-4">00000000</dd>
        </dl>
    </div>
</div>

{% include 'parciais/_carrinho.html' %}
<div class="row">
    <div class="col">
        <p class="lead text-center" >
            <strong><b>Total da compra:</b></strong> {{carrinho|cart_total_preco|estilo_moeda}}
        </p>
    </div>
</div>
<div class="row">
    <div class="col">
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'pedido:salvarpedido' %}">
            Realizar pedido e pagar
        </a>
    </div>
</div>


{% endblock body %}