config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('pedido/', include('pedido.urls')),
    path('perfil/', include('perfil.urls')),
       

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path
from . import views


app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
    path('lista/', views.Lista.as_view(), name='lista'),
]

perfil/urls.py
from django.urls import path
from . import views


app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProduto.as_view(), name='lista'),
    path('<slug>', views.DetalheProduto.as_view(), name='detalhe'),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(), name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(), name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),
    path('busca/', views.Busca.as_view(), name='busca'),
]

pedido/models.py
from django.db import models
from django.contrib.auth.models import User

class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete= models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default= 'P',
        max_length= 1,
        choices= (
        ('A', 'Aprovado'),
        ('C', 'Criado'),
        ('R', 'Reprovado'),
        ('P', 'Pendente'),
        ('E', 'Enviado'),
        ('F', 'Finalizado'),            
        )
    )
    
    def __str__(self) -> str:
        return f'Pedido {self.id} | R$ {self.total} | Status: {self.status}'

class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete= models.CASCADE)
    produto = models.CharField(max_length= 255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length= 255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField(default= 0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length= 2000)
    
    def __str__(self) -> str:
        return f'Pedido {self.pedido.id}'
    
    class Meta:
        verbose_name = 'Item do Pedido'
        verbose_name_plural = 'Itens do Pedido'

templates/parciais/_carrinho.html
{% load static %}
{% load filters %}
<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>
        
        {% for linha in carrinho.values %}
        
        <tr>
            <td class="d-none d-lg-block">                      
                
                <img class="cart-img" src="{% get_media_prefix %}{{linha.imagem}}">
            </td>
            <td>
                <a href="{% url 'produto:detalhe' linha.slug %}">
                {{linha.produto_nome}}
                </a>
                <a class="ml-3" href="{% url 'produto:removerdocarrinho' %}?vid={{linha.variacao_id}}">
                    <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                </a>
            </td>
            <td>{{linha.variacao_nome}}</td>

            <td>{{linha.quantidade}} x 
                {% if linha.preco_unitario_promocional %}
                    {{linha.preco_unitario_promocional|estilo_moeda}}
                {% else %}
                    {{linha.preco_unitario|estilo_moeda}}
                {% endif %}
                    
            </td>

            {% if linha.preco_quantitativo_promocional %}
                <td>{{linha.preco_quantitativo_promocional|estilo_moeda}}</td>
            {% else %}
                <td>{{linha.preco_quantitativo|estilo_moeda}}</td>
            {% endif %}
        </tr>
        
        {% endfor %}


    </table>
</div>

templates/parciais/_footer.html
{% load static %}
<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Feito com Django</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">Por William Aniceto</span>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js.map' %}"></script>

templates/parciais/_head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">

templates/parciais/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/parciais/_nav.html
{% load filters %}
<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'produto:lista' %}">E-Commerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Conta
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'pedido:lista' %}">Meus Pedidos</a>
                        <a class="dropdown-item" href="{% url 'perfil:criar' %}">Atualizar Cadastro</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'perfil:logout' %}">Sair</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'perfil:criar' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'perfil:criar' %}">Cadastra-se</a>
                </li>
            {% endif %}

            {% if request.session.carrinho %}
                <li class="nav-item">
                    <a class="nav-link nav-cart-link active" href="{% url 'produto:carrinho' %}">
                        <span class="nav-cart-text mr-1">
                            Carrinho
                        </span>
                        <span class="nav-cart-count mr-1">
                            <strong>{{request.session.carrinho|cart_total_quant}}x</strong>
                        </span>
                        <span class="nav-cart-icon mr-2">
                            <i class="fas fa-shopping-cart"></i>
                        </span>
                    </a>
                </li>
            {% endif %}
            
        </ul>

        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'produto:busca' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Search"
            name="termo" value="{{request.GET.termo}}">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Pesquisar</button>
        </form>
        
    </div>
</nav>

templates/parciais/_pagar.html
{% load filters %}
{% load static %}

<div class="row">
    <div class="col">
        <h3>Pedido N. {{pedido.pk}}</h3>

        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
            <div class="col-lg-4">{{pedido.pk}}</div>
            <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
            <div class="col-lg-4">{{pedido.total|estilo_moeda}}</div>

            <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
            <div class="col-lg-4">{{pedido.qtd_total}}</div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{pedido.get_status_display}}</div>
        </div>

        <div class="row mt-4">
            <div class="col">
                <h3>Produtos</h3>
            </div>
        </div>

        <div class="table-responsive mt-3">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>V.</th>
                    <th>QTD.</th>
                    <th>Total</th>
                </tr>
               
                {% for produto in pedido.itempedido_set.all %}
                <tr>
                    <td class="d-none d-lg-block">
                        <img class="cart-img" src="{% get_media_prefix %}{{produto.imagem}}">
                    </td>
                    <td>{{produto.produto}}</td>
                    <td>{{produto.variacao}}</td>
                    <td>{{produto.quantidade}}x</td>
                    {% if produto.preco_promocional %}
                        <td>{{produto.preco_promocional|estilo_moeda}}</td>
                    {% else %}
                        <td>{{produto.preco|estilo_moeda}}</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </table>
        </div>
        
    </div>
</div>

templates/parciais/_pagination.html
{% if is_paginated %}
<div class="row">
    <div class="colm">
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endif %}