config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('pedido/', include('pedido.urls')),
    path('perfil/', include('perfil.urls')),
       

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path
from . import views


app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
    path('lista/', views.Lista.as_view(), name='lista'),
]

pedido/models.py
from django.db import models
from django.contrib.auth.models import User

class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete= models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default= 'P',
        max_length= 1,
        choices= (
        ('A', 'Aprovado'),
        ('C', 'Criado'),
        ('R', 'Reprovado'),
        ('P', 'Pendente'),
        ('E', 'Enviado'),
        ('F', 'Finalizado'),            
        )
    )
    
    def __str__(self) -> str:
        return f'Pedido {self.id} | R$ {self.total} | Status: {self.status}'

class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete= models.CASCADE)
    produto = models.CharField(max_length= 255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length= 255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField(default= 0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length= 2000)
    
    def __str__(self) -> str:
        return f'Pedido {self.pedido.id}'
    
    class Meta:
        verbose_name = 'Item do Pedido'
        verbose_name_plural = 'Itens do Pedido'

pedido/views.py
from django.shortcuts import render, redirect   
from django.views.generic import ListView, DetailView
from django.views import View
from django.contrib import messages
from produto.models import Variacao
from utils import utils
from .models import ItemPedido, Pedido
from django.urls import reverse


class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')
        
        return super().dispatch(*args, **kwargs)
    
        # verificando se o pedido é do usuário que está ligado
    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(usuario= self.request.user)
        return qs
    

class Pagar(DispatchLoginRequiredMixin, DetailView):
    template_name = 'pagar.html'
    model = Pedido
    pk_url_kwarg = 'pk'
    context_object_name = 'pedido'
    


    
class SalvarPedido(View):
    
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(self.request, 'Você precisa fazer login.')
            return redirect('perfil:criar')
        if not self.request.session.get('carrinho'):
            messages.error(self.request, 'Carinho está vázio.')
            return redirect('produto:lista')
 
        carrinho = self.request.session.get('carrinho')
        # pegar as variacoes que estão no carrinho
        carrinho_variacoes_ids = [v for v in carrinho]
        
        # pegar TODAS (id__in=) as varições que estão no banco de dados
        bd_variacoes = list(Variacao.objects.select_related('produto').filter(id__in= carrinho_variacoes_ids))
       
        for varicao in bd_variacoes:
            vid = str(varicao.id)
            nome = varicao.nome
            estoque = varicao.estoque
            preco_unit = varicao.preco
            preco_unit_promo = varicao.preco_promocional
            
            
            if estoque < carrinho[vid]['quantidade']:
                carrinho[vid]['quantidade'] = estoque
                carrinho[vid]['preco_quantitativo'] = estoque * preco_unit
                carrinho[vid]['preco_quantitativo_promocional'] = estoque * preco_unit_promo
                self.request.session.save()
                messages.warning(self.request,
                                 f'Estoque do produto {varicao.produto} {nome} insulficiente para quantidade do seu carrinho')
                return redirect('produto:carrinho')
            
        qtd_total_carrinho = utils.cart_total_quant(carrinho)
        valor_total_carrinho = utils.cart_total_preco(carrinho)
                
        pedido = Pedido(
            usuario= self.request.user,
            total = valor_total_carrinho,
            qtd_total= qtd_total_carrinho,
            status= 'C',
        )
        pedido.save()
        
        ItemPedido.objects.bulk_create(
            [
                ItemPedido(
                        pedido = pedido,
                        produto = v['produto_nome'],
                        produto_id = v['produto_id'],
                        variacao = v['variacao_nome'],
                        variacao_id = v['variacao_id'],
                        preco = v['preco_quantitativo'],
                        preco_promocional = v['preco_quantitativo_promocional'],
                        quantidade = v['quantidade'],
                        imagem = v['imagem'],
                ) for v in carrinho.values()
            ]
        )
        
        
        del self.request.session['carrinho']
        
        return redirect(
            reverse('pedido:pagar', kwargs={'pk': pedido.pk})
            )


class Detalhe(DispatchLoginRequiredMixin, DetailView):
    model = Pedido
    context_object_name = 'pedido'
    template_name = 'detalhe_pedido.html'
    ordering = ['-id']


class Lista(DispatchLoginRequiredMixin, ListView):
    model = Pedido
    context_object_name = 'pedidos'
    paginate_by = 6
    template_name = 'lista_pedidos.html'
    ordering = ['-id']

pedido/templates/detalhe_pedido.html
{% extends 'base.html' %}

{% block title %}Pedido {{pedido.id}}{% endblock title %}

{% block body %}
{% include 'parciais/_messages.html' %}

{% include 'parciais/_pagar.html' %}


{% endblock body %}

pedido/templates/lista_pedidos.html
{% extends 'base.html' %}
{% load filters %}

{% block title %}Lista Pedidos{% endblock title %}

{% block body %}
{% include 'parciais/_messages.html' %}

<div class="row">
    <div class="col">
        <h3 class="mb-4">Pedidos de {{request.user}}</h3>
        <p>Abaixo todos os seus pedidos realizados na loja.</p>

        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th scope="col">Pedido</th>
                    <th scope="col">Total</th>
                    <th scope="col">Qtd. Itens</th>
                    <th scope="col">Status</th>
                    <th scope="col">Mais detalhes</th>
                </tr>

                {% for pedido in pedidos %}
                <tr>
                    <th scope="row">Pedido {{pedido.id}}</td>
                    <td>{{pedido.total|estilo_moeda}}</td>
                    <td>{{pedido.qtd_total}}</td>
                    <td>{{pedido.get_status_display}}</td>
                    <td>
                        <a href="{% url 'pedido:detalhe' pedido.id %}">
                            Ver <i class="fas fa-search-plus ml-2"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>

{% include 'parciais/_pagination.html' %}
{% endblock body %}

pedido/templates/pagar.html
{% extends 'base.html' %}
{% load filters %}
{% load static %}

{% block title %}Pagamento{% endblock title %}

{% block body %}
{% include 'parciais/_messages.html' %}
<div class="row">
    <div class="col">
        <h3>Escolha o método de pagamento</h3>
        <p>Para o desenvolvedor: adicione seu método de pagamento preferido.</p>
    </div>
</div>

{% include 'parciais/_pagar.html' %}

<div class="row mt-4">
    <div class="col">
        <a href="#" class="btn btn-primary btn-block btn-lg">Pagar</a>
    </div>
</div>

{% endblock body %}